### ISSUE TITLE
Include/Exclude not properly working as expected

### ISSUE THREAD

**Issue by muuvmuuv** [fabiospampinato/vscode-todo-plus#105]
I'm using the default ag engine and had put my directories to exclude in a .ignore file (that was the only way I got it working) and added some subdirectories to my included array in the settings. But I shows the TODOs from a libs folder. Because the double-stars are not working with ag I don't know how to exclude them.

So this is my .ignore:

```txt
/.git
/node_modules
/vendor
/logs
/cache
/dist
/assets
/libs
/tmp
/administrator
/bin
/components
/images
/includes
/jdownloads
/language
/layouts
/libraries
/media
/modules
/plugins
```

and these are the settings:

```json
{
  "todo.embedded.include": [
    "modules/mod_additive_*/**", 
    "plugins/content/additive_*/**", 
    "components/com_add*/**", 
    "templates/additive/**", 
    "modifications/**"
  ],
}
```

![screenshot 2018-08-15 at 15 04 51](https://user-images.githubusercontent.com/11534760/44149566-dee6b328-a09c-11e8-9c7a-33fb7bf89b48.png)

**Comment by fabiospampinato** [comment]
In v4.1.1 I've kind of added support for include/exclude patterns to `ag` and `rg`, it works like this:

- both `ag` and `rg` search files using their own logic (they both read your `.gitignore` file and your `.ignore` file).
- we check if every file they return is actually supposed to be included, taking into consideration the patterns you have in your include/exclude settings.

This basically means that include/exclude patterns are now fully supported except for the case where `ag`/`rg` don't return a file at all because maybe it's filtered out by your `.ignore` file but it's not filtered in your `include`/`exclude` settings.

You're seeing files from that `libs` directory because you have this pattern in your `include` setting: `"plugins/content/additive_*/**"`, and I suppose you don't have an exclude pattern for filtering this one out.

`/libs` I think means to skip the `/libs` directory, meaning the one at the root of your file system, not the one at the root of your project. If you want to skip all `libs` directory` you should put `**/libs` in there, but than again `ag` doesn't support double-star patterns so putting that into your `.ignore` file won't do a thing, you should put that into your `todo.embedded.exclude` setting instead.

I hope it's now clear how the thing works. My bad for publishing unfinished releases and creating this confusion.
