### ISSUE TITLE
Question: Is there a way to change color of statistic-based tags

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#193]
Is there a way to change the color of specific tags (est, start, done) to a different color. I like most tags to be yellow, but I would prefer to make the ones for statistics, like est to be gray so they are less distracting

**Comment by fabiospampinato** [comment]
🤔 I'm not sure, perhaps you can define those tags as special tags and give them the color that you want via these settings:

```json
  "todo.tags.names": ["critical", "high", "low", "today"], // Special tags' names
 "todo.colors.tags.background": ["#e54545", "#e59f45", "#e5d145", "#ae81ff"], // Special tags' background colors
  "todo.colors.tags.foreground": ["#000000", "#000000", "#000000", "#000000"], // Special tags' foreground colors
```

If that doesn't work perhaps you can override that with [Highlight](https://github.com/fabiospampinato/vscode-highlight).

Otherwise I don't think this should be implemented, it's too specific.

**Comment by sahil48** [comment]
That works! Thanks.

By, the way, this extension has improved dramatically since I started using it. Thanks for keeping on developing it. It's an invaluable tool for me.

**Comment by fabiospampinato** [comment]
I'm glad it's helpful to you :)
