### ISSUE TITLE
What are the uses of embedded todos

### ISSUE THREAD

**Issue by raulrfa** [fabiospampinato/vscode-todo-plus#232]
I am trying to understand the use of embedded todos, but I think it is not clear from the readme wat I can do with this kind of todos. For example it is possible to box or to done or only to list them in the tree.   Or may be there is an easy way to duplicate an embedded todo to a centralized todo.
By the way, I noticed you closed issues about the documentation, but I think it is not clear what can someone do, at least for embedded todos

**Comment by fabiospampinato** [comment]
> For example it is possible to box or to don

No, but why would you need that though, if it's done you can just delete it.

> list them in the tree

Yes, they will appear in the dedicated widget in the sidebar.

> Or may be there is an easy way to duplicate an embedded todo to a centralized todo.

I'm not sure what you mean, there's a command that lists all your embedded todos in a single file, but they generally are embedded for a reason, because they refer to some particular piece of code, so it's not like you should necessarily want to use them over standalone `.todo` files or vice versa.

> By the way, I noticed you closed issues about the documentation, but I think it is not clear what can someone do, at least for embedded todos

You can list them and that's it, basically.

**Comment by raulrfa** [comment]
Mr. Sampinato:
I think the extension is great,  but I spent hours trying to use the commands in the embedded list.  
In the documentation the line that refers to it, just explain:
Embedded todos: it's common to have //TODO or //FIXME comments in our code, this extension can find those as well.
But in my humble opinion, it does not tell us about the fact that they are a different kind of TODOS.  Just some kind of comments that you can list in the tree.
But in a software project, there is no two class of TODOS, more general tasks or more related to code, but  only tasks to control in a backlog or any other project management tool.
So, which is the command?. I think if I could be able to find a way to transfer the embedded one to a TODO file, it wiil be great. It doesn't matter that will be posible  or not to make the round-trip.
Raul

**Comment by fabiospampinato** [comment]
> So, which is the command?

There's no command for doing anything with embedded todos other than listing them.
