### ISSUE TITLE
Maintain the project structure (indentation) after moving todos to Archived 

### ISSUE THREAD

**Issue by SPascareli** [fabiospampinato/vscode-todo-plus#25]
**AS IS**:

Given a todo structure where you have:

> Project 1:
>
>- [ ] Feature 1
>    
>    - [x] Todo 1-1
>    - [ ] Todo 1-2
>    - [x] Todo 1-3

When todos nested in the structure are archived they become "flat", like in the image bellow

![](https://i.gyazo.com/7c36fb00d7cb10a1af15780f320b04a0.png)

This means that it's hard to keep the proper context of done todos.

**TO BE**:

Todos when archived still maintain their structure, by also copying the project name, and parent todo if possible, like in the image bellow:

![](https://i.gyazo.com/4d9b2009ecc16f4440a537eed373a199.png)

**Issues**:

1. What to do in the situations where the parent todo is not marked and done, but the child is?
> Perhaps would be nice to tint the parent todo to a slightly faded grey in the "archive" project, to show that it is not yet done, and when it's done show it in full normal color.

**Comment by fabiospampinato** [comment]
@SPascareli this might be a decent solution, but I don't have time for implementing it, feel free to submit a PR for it if you want 👍 

In the meantime you may just copy the project structure manually to the archive.

**Comment by fabiospampinato** [comment]
I've decided to align this extension with [PlainTasks](https://github.com/aziz/PlainTasks). Instead of maintaining the project structure we are now adding a `@project` tag to archived todos.

<img width="576" alt="screen shot 2018-05-20 at 22 26 21" src="https://user-images.githubusercontent.com/1812093/40283339-e6c5b03a-5c7c-11e8-8366-c0dec78fa415.png">
<img width="576" alt="screen shot 2018-05-20 at 22 26 31" src="https://user-images.githubusercontent.com/1812093/40283340-e6e2044c-5c7c-11e8-91ec-95a94967c980.png">
