### ISSUE TITLE
TaskPaper syntax support

### ISSUE THREAD

**Issue by metbril** [fabiospampinato/vscode-todo-plus#26]
I would really like the plugin to better support full Taskpaper syntax.

https://jessegrosjean.gitbooks.io/taskpaper/
https://taskpaper.com/

Main issue is that I'd like to use a dash `-` for both open, done or cancelled tasks.

**Comment by fabiospampinato** [comment]
TaskPaper compatibility is not a goal of this project.

If you use the dash for everything, how do you distinguish between an open/done/cancelled task?

**Comment by metbril** [comment]
In taskpaper syntax the state would be determined by the tag 'done' or 'cancel'. Open will have none of those tags.

**Comment by avelino** [comment]
emacs taskpaper implementation: https://github.com/saf-dmitry/taskpaper-mode
*for reference*

**Comment by fabiospampinato** [comment]
If anybody wants to submit a PR for this I'll be happy to consider it.

**Comment by fabiospampinato** [comment]
As I understand it, this issue is split into two separate issues: 

- Same symbols for normal/done/cancelled tasks  https://github.com/fabiospampinato/vscode-todo-plus/issues/43
- Consider any todo with the tag `@done` or `@cancelled` completed https://github.com/fabiospampinato/vscode-todo-plus/issues/44

I'm keeping this one open though, so I'll remember to update the readme about TaskPaper compatibility.

**Comment by fabiospampinato** [comment]
As of v1.18.0 the extension is now compatible with TaskPaper ✌️, just set `todo.symbols.box`, `todo.symbols.done` and `todo.symbols.cancel` to `-`. If you also want to hide the time rendered in the `@done` and `@cancelled` tag set `todo.timekeeping.finished.enabled` to `false`.

In case I forgot to cover some edge scenarios (I'm not a TaskPaper user after all), please open a new issue.
