### ISSUE TITLE
It does not stop after the estimated time has elapsed.

### ISSUE THREAD

**Issue by LeonardSSH** [fabiospampinato/vscode-todo-plus#304]
It does not stop after the estimated time has elapsed.

![yeah](https://stepbro.please-fuck.me/l1KAFM.gif)

**Comment by fabiospampinato** [comment]
The problem here is that the "started" time isn't precise to the second, when considering that and that your estimate is just 5 seconds I think stuff like that can happen. You can configure the app to output a more precise date for the "started" tag. Let me know if you can find any issues after doing that.
