### ISSUE TITLE
update vscode from 1.59 to 1.60 todo+ can`t work normally

### ISSUE THREAD

**Issue by nayoaixgnat** [fabiospampinato/vscode-todo-plus#334]
when i update vscode to 1.6,i found that todo+ can`t work,all the highlight disappeared，reload todo+ or vscode the highlight appeared but open other file an turn back it  disappear again，and shortcuts dosn`t work

**Comment by RomainJamet** [comment]
I have the same issue, with the same version of VS Code.

**Comment by pateibe** [comment]
Same issue on my installation!

**Comment by ksalab** [comment]
Same issue on my installation!

**Comment by judewang** [comment]
VS Code 1.60 has introduced the "Automatic language detection" and it mis-detected some files at v1.60.

Please try to update to v1.60.1, some bugs can be fixed by just updating to the latest version of vscode.

https://github.com/fabiospampinato/vscode-todo-plus/issues/331
https://github.com/fabiospampinato/vscode-todo-plus/issues/332
https://github.com/microsoft/vscode/issues/132571

**Comment by fabiospampinato** [comment]
It looks like this got fixed in vscode.
