### ISSUE TITLE
[Feature Request] - Navigate via "Go to symbol"

### ISSUE THREAD

**Issue by trianta** [fabiospampinato/vscode-todo-plus#34]
Hi Fabio

any chance you will enable "go to symbol" (sh-cmd-O) using -for example- markdown header styles (#, ##, etcetera)?

Grazie for the work by the way, it is a major reason I migrated to vscode

**Comment by fabiospampinato** [comment]
Hey, thank you :)

I don't like having to add support for some new syntax for this, and I don't think this is a particularly useful feature for most people, but I'll consider a PR that adds support for "Go To Symbol" if the symbols are basically all the "projects" in the file, so that one can switch quickly between them.

**Comment by trianta** [comment]
Yes! Going to projects is just fine. Thanks ;)

**Comment by fabiospampinato** [comment]
Duplicate of #19
