### ISSUE TITLE
Add new statistics tokens: [lasted], [wasted] and [elapsed]

### ISSUE THREAD

**Issue by samael205** [fabiospampinato/vscode-todo-plus#65]
Hello,

I see that we have the token [est] that tells you the estimated time of a task, and this appears in todo.statistics.project.text. You could add a new token that is [last] that also tells you the total time the project lasted

**Comment by loktionov129** [comment]
Hello, @fabiospampinato 

The new tokens do not correctly form time. They get calculated seconds from host machine time.
For example:

I Have TODO file:
```
TodoPlus:
  Open:
    [ ] Fix bugs with tokens
```

### 18-06-12 19:23:42
I am going to line 3 and pressing ALT+S
```
TodoPlus:
  Open:
    [ ] Fix bugs with tokens @started(18-06-12 19:23)
```

### 18-06-12 19:23:49
I am pressing ALT+D
```
TodoPlus:
  Open:
    ✔ Fix bugs with tokens @started(18-06-12 19:23) @done(18-06-12 19:23) @lasted(49s)
```

---

I think would be better if you provide correct seconds for this case. It should be a `7s` instead of `49s`.
Or is it better not to show seconds at all?

**Comment by jods4** [comment]
👍 
`[lasted]` would be very nice, it makes time-tracking a lot more useful.
Given that we already have `@est` + `[est]` and `@lasted`, it should be pretty straight-forward to add?

Additional stuff such as `[wasted]` and `[elapsed]` can be added later.

**Comment by fabiospampinato** [comment]
It shouldn't be too difficult ti implement, but doing it in a performant way is a little more trickier.

**Comment by jods4** [comment]
Maybe I can have a look and submit a PR, what makes `[lasted]` more difficult than `[est]`?

**Comment by fabiospampinato** [comment]
They are quite similar actually, if you want to submit a PR I think most, if not all, of the code should go [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/utils/statistics.ts).

I'd like if anything related to `[lasted]` wouldn't be computed if that's not used anywhere, same for `[est]`, this is currently not the case, the replacement values for `[est]` are computed even if that's not used anywhere.

**Comment by jods4** [comment]
I had a look. Adding `[lasted]` and `[wasted]` would be quite easy... if doing it the way it's done today.

If you don't want to do that work then there are two options, both a big change to the current code:

- Do it lazily in a token getter -> requires keeping the list of items and computing tokens on demand. Would do wonders if decorations were only updated for items in view (are they?).

- Do it based on config templates. Not too hard except if you want to support updating the config. That means getting an update notification (there's none in the code base) and re-updating stats in that event (needs all items, etc.)

Third option: I'm pretty sure the cost of those extra tokens could be made very small, maybe even faster than today (even when always computed).
The 3 statistics could be combined in a single reduce pass. Adding integers is peanuts, the main work is running all the regexes... which are not anchored on start of string (`@est` can't because it's used elsewhere without anchor). Just add a switch on the second character to only match the tag if it has a chance to match... That should make the code faster overall than it is today, even with the 2 new tokens.

**Comment by jods4** [comment]
BTW: the most performant way to approach this problem is probably to use a trie to classify "interesting" tags as they are found when parsing each line.

**Comment by fabiospampinato** [comment]
> Would do wonders if decorations were only updated for items in view (are they?).

Nope, everything gets redecorated. Which is actually the root cause of our [scaling problems](https://github.com/fabiospampinato/vscode-todo-plus/issues/54), we can't just redecorate the current line or something, everything must be redecorated. https://github.com/Microsoft/vscode/issues/50346

In theory one could divide the document in blocks of 100 lines or something and redecorate only those blocks that changed. Never mind how complicated the code will get, but this is impossible to implement because decorations might get trashed away and there's no way of knowing when that happens. https://github.com/Microsoft/vscode/issues/50415

> the main work is running all the regexes... which are not anchored on start of string (`@est` can't because it's used elsewhere without anchor)

I'm not sure what you mean by "anchor" here. 

One could use the same approach that I described earlier, and basically cache the result of running those regexes on portions of the document, but I'm not sure this is worth pursuing.

I'm not sure using a trie would help much, I think the most expensive portion of the code is, as you said, just running the regexes, which we also need to run for decorating the document.

IMHO we should proceed as following:

- Just implement `[lasted]` the same way I've implemented `[est]`
- Check how much extra processing time computing `[lasted]` requires with the attached file
- If it's significant (probably), in comparison to the overall time required for decorating the whole document then:
  - Make a function that checks if `est`/`lasted`/etc. are used in the following settings:
    - `todo.statistics.project.enabled`
    - `todo.statistics.project.text` 
    - `todo.statistics.statusbar.enabled`
    - `todo.statistics.statusbar.text` 
    - `todo.statistics.statusbar.tooltip` 
  - If they are not, don't compute them at all
  - Be sure to refresh the result of this function when the configuration changes
- While you're at it you might as well implement `[wasted]` and `[elapsed]` too.

What do you think?

[performance2.todo.zip](https://github.com/fabiospampinato/vscode-todo-plus/files/2435922/performance2.todo.zip)

**Comment by jods4** [comment]
I can add `lasted` and `wasted` in a way that I don't think impacts perf compared to current version. 
You can check if the results are good enough or not.

As discussed, optimizing that work away is possible but requires bigger changes.

What should `elapsed` be?

**Comment by fabiospampinato** [comment]
`elapsed` is the sum of `lasted` and `wasted`.

**Comment by jods4** [comment]
PR is ready
