### ISSUE TITLE
improve "Enter" key

### ISSUE THREAD

**Issue by Quentigus** [fabiospampinato/vscode-todo-plus#74]
When I press the "enter" key and the cursor is placed before the tags, they go to the next line.
It would be more convenient if they stay on the same line

Thanks

**Comment by fabiospampinato** [comment]
Does this happen after you accept a tag completion? (Type `@` and then select one of the suggested tags)

Can you post here a screenshot of the issue, or even better a GIF? I'm not quite sure if I understood the issue correctly.

**Comment by fabiospampinato** [comment]
Oh I see, thanks a lot for the recording. This is done on purpose, in most of the cases I think this is what you want to happen.

Instead of writing the content of the todo and then running `Todo: Toggle Box` you should do the opposite.

**Comment by Quentigus** [comment]
When I do "toggle box" I've the same result :(

It would be interesting if there is the same behavior as the (X) after the name of a project

**Comment by fabiospampinato** [comment]
> When I do "toggle box" I've the same result :(

You're right, sorry, I think I was thinking about how it worked before I pushed the commit for repositioning the cursor, which is the thing you don't like. Before that commit you couldn't just create a todo and then just write it's content, because if you had the `@created` tag enabled your cursor would be positioned after it. That's basically the problem it fixes.

For your use case just go to the end of the line (cmd+right on macOS) and then press enter, or create multiple empty lines in advance and then just go down. Alternatively there's a command in VSC that does this for you: `editor.action.insertLineAfter`, by default on macOS it's bound to `cmd+enter`, which this extension overrides, you could just remap it to something else and use it.

It's a bit of labour but I think the advantages outweigh the disadvantages.

> It would be interesting if there is the same behavior as the (X) after the name of a project

Not possible, those statistics after the projects are computed from the content of the file itself, there's no way to know when a todo has been created without writing the date somewhere in the file first.
