### ISSUE TITLE
View feedback

### ISSUE THREAD

**Issue by nealot** [fabiospampinato/vscode-todo-plus#92]
Hey, I switched over from Todo-Tree because your extensions are always really impressive. I know you've only just added the todo view, but here are my suggestions for features:

1. Custom icons
2. Fix '/' character for file names (see below)
![screenshot_20180809_210031](https://user-images.githubusercontent.com/36805289/43933368-559268a8-9c17-11e8-8697-815dd54844a6.png)
3. Remove extra space between icon and description

**Comment by fabiospampinato** [comment]
> Hey, I switched over from Todo-Tree because your extensions are always really impressive

Thanks :)

> Custom icons

You can have them in custom colors already, isn't this enough?

> Fix '/' character for file names (see below)

I replace the forward slash with another character because of this issue https://github.com/Microsoft/vscode/issues/56106. But it's not properly rendered in your system (damn Windows!), in v4.0.4 I'm not using the normal forward slash, but I had to remove the filetype icons.

> Remove extra space between icon and description

There's no extra space that I can remove, the icons are a little smaller than those used by todo-tree, and I think VSC allocates a fixed amount of space to the icon, so that's why there seems to be some extra padding going on. IMHO todo-tree's icons are too big.

**Comment by nealot** [comment]
Oh darn, those file icons were really helpful :(

**Comment by fabiospampinato** [comment]
You may want to comment on that issue I linked, maybe they'll fix the problem in the next iteration.

**Comment by fabiospampinato** [comment]
> Fix '/' character for file names (see below)

Fixed properly in v4.0.5, with filetype icons supports.
