### ISSUE TITLE
Performance in big projects

### ISSUE THREAD

**Issue by PixelT** [fabiospampinato/vscode-todo-plus#96]
I just installed magento2 on my localhost.
There is a lot `TODO``BUG``FIX` and other tags  in magento files, for example when I search `TODO` in files I have:
`915 results in 385 files`
When I try to open TODO section, I have infinite loading there, which finally hang the editor

I thought when I set this:
```
"todo.embedded.include": [
        "todo.todo"
    ],
```
It will search ONLY in this one file, but it doesn't work in this way?

**Comment by fabiospampinato** [comment]
I've just tried the extension with a project of mine containing about 700 embedded todos, and it takes 5 seconds to fetch them in my machine. Performance should degrade not with the number of todos, but with the number of files and lines, maybe magento2 has lots of those.

Anyway subsequent refreshes should be pretty quick, aren't they?

> It will search ONLY in this one file, but it doesn't work in this way?

It should work that way, but it's looking for thinks like `//TODO: foo`, which you're probably not going to write in your `todo.todo` file.

There's a "File" view that extracts todos from that file.

**Comment by fabiospampinato** [comment]
I've optimized the hell out of this, install [ag](https://github.com/ggreer/the_silver_searcher) on your system and finding todos will be like 50 times faster. On magento2, it went down from 210 seconds to 4 seconds on my system.

Unfortunately the whole thing might still take a bit, because VSC itself is quite slow at rendering the tree https://github.com/Microsoft/vscode/issues/56234.
